
image: continuumio/miniconda3:latest

before_script:
  - export PIP_CACHE_DIR="/opt/cache/pip"
  - conda env create -f environment.yml
  - source activate ingest

cache:
    paths:
        - testdata/

unittests:
  stage: test
  script:
    - source test.sh
